camunda:
  migrator:
    auto-ddl: true
    c7:
      data-source:
        auto-ddl: true

logging:
  level.io.camunda.migrator: DEBUG
  level.org.camunda.bpm.engine.impl.persistence.entity.HistoricProcessInstanceEntity: DEBUG
  level.io.camunda.migrator.qa.variables.TestVariableInterceptor: INFO
