migrator:
  c7.auto-ddl: true
  rdbms-exporter.auto-ddl: true

logging:
  level.io.camunda.migrator: DEBUG
  level.org.camunda.bpm.engine.impl.persistence.entity.HistoricProcessInstanceEntity: DEBUG

camunda:
  database:
    database-vendor-id: h2