spring.datasource:
  url: jdbc:h2:~/Downloads/c8_rdbms.db;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
  #  url: jdbc:postgresql://localhost:5432/process-engine # for PostgreSQL or CockroachDB
  #  url: jdbc:mysql://localhost:3306/process-engine?sendFractionalSeconds=false
  #  url: jdbc:mariadb://localhost:3306/process-engine
  #  url: jdbc:oracle:thin:@localhost:1521:ORCL
  #  url: jdbc:db2://localhost:50000:engine
  #  url: jdbc:sqlserver://localhost:1433;databaseName=processEngine
  username: sa
  password:
  driver-class-name: org.h2.Driver
#  driver-class-name: org.postgresql.Driver # for PostgreSQL or CockroachDB
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  driver-class-name: org.mariadb.jdbc.Driver
#  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  driver-class-name: oracle.jdbc.OracleDriver
#  driver-class-name: com.ibm.db2.jcc.DB2Driver
spring:
  liquibase:
    change-log: db/changelog/rdbms-exporter/changelog-master.xml
mybatis:
  mapper-locations: classpath:mapper/**/*-mapper.xml
