camunda:
  migrator:
    c7:
      data-source:
        auto-ddl: true
        jdbc-url: jdbc:h2:~/Downloads/c8_rdbms-source.db;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver

#logging.level."org": DEBUG
