name: Setup Maven
description: |
  Maven wrapper to abstract defaults for setting maven up
inputs:
  java-version:
    description: Java version to be used
    required: false
    default: '21'
  distribution:
    description: Java distribution to be used
    required: false
    default: 'temurin'
  maven-version:
    description: Maven version to be used
    required: false
    default: '3.8.6'
  secrets:
    description: JSON wrapped secrets for easier secret passing
    required: true
runs:
  using: composite
  steps:
  - name: Import secrets
    id: secrets
    uses: hashicorp/vault-action@7709c609789c5e27b757a85817483caadbb5939a
    with:
      url: ${{ fromJSON(inputs.secrets).VAULT_ADDR }}
      method: approle
      roleId: ${{ fromJSON(inputs.secrets).VAULT_ROLE_ID }}
      secretId: ${{ fromJSON(inputs.secrets).VAULT_SECRET_ID }}
      # TODO update with cambpm secret
      secrets: |
        secret/data/products/optimize/ci/optimize NEXUS_USERNAME;
        secret/data/products/optimize/ci/optimize NEXUS_PASSWORD;
  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      java-version: ${{ inputs.java-version }}
      distribution: ${{ inputs.distribution }}
      cache: "maven"
  - name: Setup Maven
    uses: stCarolas/setup-maven@v5
    with:
      maven-version: ${{ inputs.maven-version }}
  - name: 'Create settings.xml'
    uses: s4u/maven-settings-action@64e42c454dbd42ef6370ac8539685755aedd205b # v3.1.0
    with:
      githubServer: false
      servers: |
        [{
          "id": "camunda-nexus",
          "username": "${{ steps.secrets.outputs.NEXUS_USERNAME }}",
          "password": "${{ steps.secrets.outputs.NEXUS_PASSWORD }}"
        }]
      mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "*", "name": "camunda Nexus"}]'
  - shell: bash
    run: |
      sudo rm -rf /etc/localtime
      sudo ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
