name: Setup Maven
description: |
  Maven wrapper to abstract defaults for setting maven up
inputs:
  java-version:
    description: Java version to be used
    required: false
    default: '21'
  distribution:
    description: Java distribution to be used
    required: false
    default: 'temurin'
  maven-mirrors:
    description: |
      JSON list of extra Maven mirrors.
      It will be merged with Camunda Nexus settings (if enabled ), with precedence."
    required: false
    default: '[]'
  maven-servers:
    description: |
      JSON list of extra Maven servers.
      It will be merged with Camunda Nexus settings (if enabled), with precedence."
    required: false
    default: '[]'
  maven-version:
    description: Maven version to be used
    required: false
    default: '3.8.6'
  secrets:
    description: JSON wrapped secrets for easier secret passing
    required: true
runs:
  using: composite
  steps:
  - name: Import secrets
    id: secrets
    uses: hashicorp/vault-action@7709c609789c5e27b757a85817483caadbb5939a
    with:
      url: ${{ fromJSON(inputs.secrets).VAULT_ADDR }}
      method: approle
      roleId: ${{ fromJSON(inputs.secrets).VAULT_ROLE_ID }}
      secretId: ${{ fromJSON(inputs.secrets).VAULT_SECRET_ID }}
      secrets: |
        secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_USR;
        secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_PSW;
  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      java-version: ${{ inputs.java-version }}
      distribution: ${{ inputs.distribution }}
      cache: "maven"
  - name: Setup Maven
    uses: stCarolas/setup-maven@v5
    with:
      maven-version: ${{ inputs.maven-version }}
 # Camunda Nexus and extra mirrors/servers must be merged on ids (extra values have precedence).
  - name: Get Maven mirrors and servers to use
    id: maven
    env:
      # Camunda Nexus is disabled for fork PRs
      CAMUNDA_NEXUS_ENABLED: >-
        ${{
          steps.is-fork.outputs.is-fork != 'true' &&
          inputs.camunda-nexus == 'true'
        }}
      CAMUNDA_NEXUS_MAVEN_MIRROR: >-
        [{
          "id": "camunda-nexus",
          "name": "Camunda Nexus",
          "url": "https://repository.nexus.camunda.cloud/content/groups/internal/",
          "mirrorOf": "zeebe,zeebe-snapshots"
        }]
      EXTRA_MAVEN_MIRRORS: ${{ inputs.maven-mirrors }}
      EXTRA_MAVEN_SERVERS: ${{ inputs.maven-servers }}
    run: |
      # If Camunda Nexus is disabled, reset default mirrors/servers to empty lists
      if [ "${CAMUNDA_NEXUS_ENABLED}" != "true" ]; then
        CAMUNDA_NEXUS_MAVEN_MIRROR="[]"
      fi

      # Use jq 'add' operator to merge grouped sublists
      mirrors=$(\
        jq -n \
        --argjson nexus_mirror "${CAMUNDA_NEXUS_MAVEN_MIRROR}" \
        --argjson maven_mirrors "${EXTRA_MAVEN_MIRRORS}" \
        '[ $nexus_mirror + $maven_mirrors | group_by(.id)[] | add ]'
      )
      servers=$(\
        jq -n \
        --argjson nexus_server "${CAMUNDA_NEXUS_MAVEN_SERVER}" \
        '[ $nexus_server + $maven_servers | group_by(.id)[] | add ]'
      )

      echo mirrors=$mirrors >> $GITHUB_OUTPUT
      echo servers=$servers >> $GITHUB_OUTPUT
    shell: bash
  - name: Update Maven settings.xml
    uses: s4u/maven-settings-action@v3.1.0
    with:
      githubServer: false
      servers: ${{ steps.maven.outputs.servers }}
      mirrors: ${{ steps.maven.outputs.mirrors }}