name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_USR;
            secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_PSW;

      - name: Setup Maven
        uses: ./.github/actions/setup-maven
        with:
          vault-address: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

      - name: Build and run default tests
        run: mvn clean install --batch-mode

      - name: Run tests with PostgreSQL
        run: mvn test -Dpostgresql

      - name: Run tests with Oracle
        run: mvn test -Doracle

      - name: Collect distro
        id: distro
        if: github.ref == 'refs/heads/main'
        run: |
          ARTIFACT_DIR=$(mktemp -d)
          cp assembly/target/c7-data-migrator-assembly-*.tar.gz "${ARTIFACT_DIR}/"
          cp assembly/target/c7-data-migrator-assembly-*.zip "${ARTIFACT_DIR}/"
          echo "dir=${ARTIFACT_DIR}" >> $GITHUB_OUTPUT

      - name: Upload distro
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: distro
          path: ${{ steps.distro.outputs.dir }}
          retention-days: 7
